name: Example workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'Zulu'
          java-version: '8'
      - name: Unittests
        run: |
          ./gradlew clean test
      - name: Integ tests
        run: |
          ./gradlew integTest
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/test-results/**/*.xml"
